[ADD] website_event_baidu_map
OCA/l10n-china pull request #31
Opened 2017-02-23 08:19 UTC by victormartinelicocorp

2017-02-23 08:20 UTC, victormartinelicocorp commented
Please review @elicoidal

2017-02-24 01:40 UTC, elicoidal commented
@victormartinelicocorp Can you add travis and coverall for this repo?

2017-02-24 02:34 UTC, elicoidal requested changes
mostly some formal changes

2017-02-24 02:34 UTC, elicoidal commented on website_event_baidu_map/README.rst
> +* Go to Settings/Parameters/System Parameters and create a record which Key must be named baidu.api and the Value like [http://api.map.baidu.com/api]?v=[2.0]&ak=[your ak].
use enumerated list better

2017-02-24 02:34 UTC, elicoidal commented on website_event_baidu_map/README.rst
> +This module is maintained by Elico Corporation.
use OCA template

2017-02-24 02:34 UTC, elicoidal commented on website_event_baidu_map/__openerp__.py
> +    'website': 'https://www.elico-corp.com, https://odoo-community.org',
remove second website

2017-02-24 02:34 UTC, elicoidal commented on website_event_baidu_map/__openerp__.py
> +    'data': [
add support key

2017-02-24 02:34 UTC, elicoidal commented on website_event_baidu_map/README.rst
> +
Add Runbot and Issue section from standard OCA template

2017-11-03 06:05 UTC, elicoidal commented
@victormartinelicocorp I think this one could be finished easily

2019-05-29 14:17 UTC, victormmtorres commented
v9 is old version

2019-05-29 14:17 UTC, closed without merging