[WIP][9.0] Improve the calculation of current Payroll rules and fix travis
OCA/l10n-china pull request #36
Opened 2017-04-20 04:05 UTC by Wizr

2017-04-20 05:49 UTC, martintorresvm requested changes
@Wizr Create a separated PR just to add Travis File

2017-04-20 06:07 UTC, Wizr commented
Travis file added #37 , but runbot test failed. This PR fix the problem, so they blocked each other. What to do next?

2017-04-20 06:39 UTC, victormartinelicocorp commented
@Wizr I think is normal

https://runbot2.odoo-community.org/runbot/static/build/3286675-37-61a868/logs/job_20_test_all.txt

We need to fix or know if the message `codecov/project — No report found to compare against`  is normal

So for Runbot #37 IMO is normal.
Waiting for OCA reviewers if they could help

2017-04-20 08:32 UTC, elicoidal requested changes
Please remove the travis file
Needs functional testing by Linda

2017-04-20 08:32 UTC, elicoidal commented on .travis.yml
> +language: python
remove from this PR

2017-05-12 10:36 UTC, martintorresvm approved these changes

2017-05-12 11:32 UTC, elicoidal approved these changes

2017-05-12 11:33 UTC, elicoidal commented
Waiting for functional tests to merge @Wizr @victormartinelicocorp

2017-05-16 10:17 UTC, Wizr commented
Linda has tested, and found no issues.

2017-05-16 13:58 UTC, merged